packaging_format = 2

id = "helloworld"
name = "Hello World"
description.en = "A dummy basic app to illustrate YunoHost's app packaging."
description.fr = "Une app simple et bidon pour illustrer comme le packaging d'app de YunoHost fonctionne"

version = "0.1~ynh2"

maintainers = ["alexAubin"]

[upstream]
license = "WTFPL"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = false
ldap = "not_relevant"
sso = "not_relevant"
disk = "1M"
ram.build = "1M"
ram.runtime = "1M"

[install]
    [install.domain]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "domain"

    [install.path]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "path"
    default = "/helloworld"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.categories]
    ask.fr = "Vous pouvez éditer un fichier .csv pour personnaliser les catégories d'annonces en suivant cet exemple du fichier origninal par défaut categories.cvs https://framagit.org/anto1ne/petitesannonces/-/blob/master/bdd/categories.csv?ref_type=heads&plain=1."
    help.fr  = "Pour cela, Téléchargez le ici https://framagit.org/anto1ne/petitesannonces/-/raw/master/bdd/categories.csv?ref_type=heads&inline=false, éditez-le avec votre éditeur de texte en respectant son format (bien garder les `1;` , `2;`, etc..."
    type = "file"
    accept = [".csv"]
    bind = "/tmp/categories.csv"
    redact = true
    optional = true

    [install.regions]
    ask.fr = "Vous pouvez éditer un fichier .csv pour personnaliser les lieux des annonces en suivant cet exemple du fichier origninal par défaut regions.cvs https://framagit.org/anto1ne/petitesannonces/-/blob/master/bdd/regions.csv?ref_type=heads&plain=1."
    help.fr = "Pour cela, Téléchargez le ici https://framagit.org/anto1ne/petitesannonces/-/raw/master/bdd/regions.csv?ref_type=heads&inline=false, éditez-le avec votre éditeur de texte en respectant son format (bien garder les `1;`, `2;`, etc...)"
    type = "file"
    accept = [".csv"]
    bind = "/tmp/regions.csv"
    redact = true
    optional = true

[resources]
    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"
